### ISSUE TITLE
Ability to give different responses for a same polling request

### ISSUE THREAD

**Issue by swapnasavant** [sideshowcoder/canned#106]
I have a RestAPI which I poll from UI to get status of an operation. The API returns inprogress/success/failure for the same request. 
I need to mock this API to first show inprogress and then succeeded. 

Is there any way I can do this with canned?

**Comment by sideshowcoder** [comment]
Sorry for the late response, this is currently not possible directly as canned maps to files, however in case your api sends different parameters this can be accomplished through the use of multiple responses (in one file) matching the request parameters.
