### ISSUE TITLE
test '#49' fails on master branch

### ISSUE THREAD

**Issue by sanstream** [sideshowcoder/canned#120]
running `npm test` or `make test`
Gives this output:
```
> canned@0.3.10 test /home/sanne/Projects/bankai/canned
> make test

./node_modules/.bin/jasmine-node --captureExceptions spec
...................................................SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.res.end (/home/sanne/Projects/bankai/canned/spec/canned.spec.js:620:29)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
Makefile:7: recipe for target 'test' failed
make: *** [test] Error 1
npm ERR! Test failed.  See above for more details.
```

**Comment by sideshowcoder** [comment]
Is this still happening for you? I tried locally with the latest version and it seems to run through fine for me. What System are you on, I'm wondering if it is a version related issue?

I'm on Ubuntu 17.04, node v6.11.4 currently.

**Comment by sideshowcoder** [comment]
This test is no longer relevant and has been removed.

**Comment by sanstream** [comment]
Sorry for the late response. I am on holiday 😏

I'm fine btw with it being closed since I made this issue as a FYI anyway.

Thank you for building this project.

Sanne Peters
