### ISSUE TITLE
How are sym linked folders (with data) handled?

### ISSUE THREAD

**Issue by kavithabhaskaran** [sideshowcoder/canned#44]
So when I have the Canned API server running and I make changes to a an "index.get.json" file, I do not have to restart my server (verified that and it works fine). I can continue sending requests and get responses (including the updated data from index.get.json). My question is if I have all the data in a folder called "Abc" and I sym link it  "Def" in such a way that any requests that I send to "Abc" should be re-directed to "Def", that does not seem to work unless I re-start the canned API server. How is that handled/supposed to be handled in the source code?

**Comment by sideshowcoder** [comment]
I'm closing this since it seems unrelated to to canned internal stuff.
