### ISSUE TITLE
Canned server crashed when I try to run a Python script using subprocess module

### ISSUE THREAD

**Issue by kavithabhaskaran** [sideshowcoder/canned#47]
Hi Phil:

I have 2 scenarios here:

Scenario #1 (Works fine).

When I start canned API server on Python >> (Python CLI prompt)

```
>>> subprocess.Popen(["./startAPIServer"],stdout=subprocess.PIPE)                               
<subprocess.Popen object at 0x7f48c5825b10>
```

and run the "python add.py" (which does a curl POST) on regular $ prompt, everything works fine and dandy as expected.

```
$ python add.py
IP is 192.168.1.15
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   165  100   132  100    33   1848    462 --:--:-- --:--:-- --:--:--  1859
```

Values of Controller IDs and Controller Names that were successfully added. 

---

Scenario #2.(Canned Server crashes and js error)

When I run both startServer script and add.py from python interactive mode,

```
>>> subprocess.Popen(["./startAPIServer"],stdout=subprocess.PIPE)
<subprocess.Popen object at 0x7f48c5825b10>
>>> subprocess.call("python add.py", shell=True,stderr=subprocess.PIPE)
IP is 192.168.1.15
```

Values of Controller IDs and Controller Names that were successfully added.

```
>>> 
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write EPIPE
    at errnoException (net.js:901:11)
    at Object.afterWrite (net.js:718:19)
```

As you have seen, Scenario #2 also works but after 4-5 seconds, I get the error message (which I presume if from Canned) and the Canned server crashes. Would you know why it would crash??

Just to clarify, the "add.py" does this : 

```
proc = subprocess.Popen(["curl -X POST -i -H \"Content-type: application/json\" -X POST http://localhost:8080/v1/controllers -d '{\"url\": \"http://%s:%d\"}'" % (ip, i)], stdout=subprocess.PIPE, shell=True)
(out, error) = proc.communicate()
```

**Comment by Schmelter** [comment]
In case people are still running into this, here's how I solved it.  Basically, if I didn't set a STDIN/STDOUT/STDERR for the Popen call, it seemed to work.

Startup.POPEN_CANNED = subprocess.Popen(['canned -p 3000 %s' % props.mockBase], shell=True, preexec_fn=os.setsid)

The POPEN_CANNED variable is just a static class variable to the returned Popen so that I can shutdown canned later with:

Startup.POPEN_CANNED.terminate()
Startup.POPEN_CANNED.wait()

Hope that helps.

**Comment by sideshowcoder** [comment]
Awesome thanks for the tip!
