### ISSUE TITLE
Serve custom HTTP headers on responses

### ISSUE THREAD

**Issue by brendan-rius** [sideshowcoder/canned#69]
I would like to be able to add custom HTTP headers on responses so I can fake - for example - the login process (which returns a `Authorization` header)

**Comment by sideshowcoder** [comment]
That is possible, take a look at https://github.com/sideshowcoder/canned#variable-responses using the `header`.

**Comment by brendan-rius** [comment]
As I understand it, it is possible to change the response being sent depending on the request headers. But I would like to add custom HTTP headers to the request.

I implemented this locally because it could not find it anywhere in the documentation/code

**Comment by sideshowcoder** [comment]
Ah sorry I see, yes that is currently not possible, yet it has been done specifically for the CORS headers but nothing else so far... PR would be very welcome.

**Comment by brendan-rius** [comment]
PR #70 should solve this
