### ISSUE TITLE
Get different response thank to params in json files doesn't works

### ISSUE THREAD

**Issue by xdemocle** [sideshowcoder/canned#73]
I set my json file for multiple responses like below
```javascript
//! params: {"limit": 40, "offset": 0}
{
  "name": "value1"
}

//! params: {"limit": 40, "offset": 40}
{
  "name": "value2"
}
```

But canned continue to deliver only the first response, despite I use a different query_list.
Any idea?

**Comment by sideshowcoder** [comment]
Just edited a comment for more readablilty... I'm trying it out.

**Comment by sideshowcoder** [comment]
yes this is a bug I just tried it and it seems to ignore the 2. param if the first matches. I created a test for it to work towards fixing if you want to look into it feel free :)

**Comment by xdemocle** [comment]
cool, thanks. is a good tool for mockup data. Congrats

**Comment by xdemocle** [comment]
I'm working on it... cause I really need it :dancer:

**Comment by sideshowcoder** [comment]
awesome :+1:

**Comment by xdemocle** [comment]
FYI, the canned npm package is still the 0.3.4v

**Comment by sideshowcoder** [comment]
Oh shot ... I know there was something I missed sorry about that...

**Comment by sideshowcoder** [comment]
It's up now, thanks for the reminder :+1:

**Comment by xdemocle** [comment]
ehhehe cool :) thank you

**Comment by git-jiby-me** [comment]
@sideshowcoder , @xdemocle I think this have been fixed, but not closed ?

**Comment by xdemocle** [comment]
yep... exactly. thanks to close it :dancer:
