### ISSUE TITLE
Canned breaks if params contains strange characters

### ISSUE THREAD

**Issue by xdemocle** [sideshowcoder/canned#75]
Canned breaks if params contains strange characters.
Like: - + %20 etc.

Example:
```
//! params: {"category": "jonge-vrouwen", "limit": 40, "offset": 0, "withPhotos": 1}
```

**Comment by xdemocle** [comment]
Looks like is the regex below that break the matched lines:

var requestMatch = new RegExp(/\/\/! [body|params|header]+: ([\w {}":,@.]*)/g)

**Comment by xdemocle** [comment]
I temporary resolved like below. But i'm not a RegExp expert.
```
var requestMatch = new RegExp(/\/\/! [body|params|header]+: ([\w {}":\-\+\%,@.]*)/g)
```

**Comment by sideshowcoder** [comment]
If it passes the test I'm good with it mind sending a PR?

**Comment by xdemocle** [comment]
Nope, I don't mind... I was just gonna fork
