### ISSUE TITLE
Doesn't consider Accepts Header to decide to return HTML or JSON

### ISSUE THREAD

**Issue by git-jiby-me** [sideshowcoder/canned#80]
If i have one GET endpoint, returning HTML and JSON based on Accepts header, it always delivers the HTML content whatever be the  Accepts Header.

As far as i see, if there is HTML and JSON responses for a endpoint, canned should check the Accepts Header to decide which content to sent

**Comment by git-jiby-me** [comment]
Submitted a pull request introducing this fix, https://github.com/sideshowcoder/canned/pull/81

**Comment by sideshowcoder** [comment]
closed via #81
