### ISSUE TITLE
Canned crashes when using query string parameters

### ISSUE THREAD

**Issue by targoo** [sideshowcoder/canned#97]
node version: v6.1.0
Whenever you try to use query string parameters canned crashed with the following message

if(source.hasOwnProperty(prop)){
  TypeError: source.hasOwnProperty is not a function

**Comment by targoo** [comment]
here is the PR to fix it: https://github.com/sideshowcoder/canned/pull/98

**Comment by sideshowcoder** [comment]
fixed thanks 👍
